### PR TITLE
Remove deleteUser assert

### PR DESCRIPTION
**Pull request by holm**
This removes a very specific assert on the exact format of the message. We found that this message have changed.

I do not think it is reasonable to expect an API to have unchangeable wording of messages.

### CODE REVIEW

**Comment by ruimarinho** [comment]
While I couldn't agree more with you, unfortunately history doesn't play well for Authy on this one. I've experienced a 200 OK where the message was something like "the user was not deleted" 🤷‍♂️

In any case, a lot of time has passed so let's assume this is a thing of the past. Can you fix the PR so that the tests are fixed (i.e. removed) as well? Not sure why Travis didn't pick this build. I've refreshed the config so let's see if the next push activates CI.

**Comment by ruimarinho** [comment]
@holm are you still interested in making this PR?

**Comment by holm** [comment]
Sure. I forgot about it, but I can have a look at the tests

**Comment by holm** [comment]
I removed the two obsolete tests now

**Comment by ruimarinho** [comment]
Thanks!

**Pull request merged**
